### ISSUE TITLE
特地来感谢 finger-mover

### ISSUE THREAD

**Issue by kele59** [HcySunYang/finger-mover#1]
在 V2 上看到了帖子，特地跑来 GitHub 体验了一下，感觉这几点做的非常好：
1. 文档非常全，中英文都有，点赞！
2. 每个插件都有对应的例子，涵盖了常见的功能，还有在线体验二维码，很直观，很贴心！
3. 文档中的示例代码很简洁易懂，还有注释，再次点赞！
4. 用 QQ，微信内置的浏览器，以及 UC 都简单测试了下，没有发现问题，Good！

维护一个开源项目特别不容易，特地跑来点赞！（我可不是托啊😂）

**Comment by HcySunYang** [comment]
Thank you very much recognition and support,When you use this project in the process of encounter problems, welcome to open an issue,I will be timely feedback.（译：非常感谢你的认可和支持，当你使用这个项目的过程中遇到问题时，欢迎打开一个issue，我一定会及时反馈）
