### ISSUE TITLE
当数据添加到列表的头部的时候，调用refresh没有效果

### ISSUE THREAD

**Issue by 429365799** [HcySunYang/finger-mover#10]
this.fm = new Fmover({
            el: '#scroll-container-main',
            plugins: [
                simulationScrollY({
                    onTransMove: async (currentY) => {
                        if (!this.loadPreLock && currentY <= 100 && currentY > 0) {
                            console.log('到顶了');
                            this.loadPreLock = true;
                            
                            try {
                                // 加载数据，列表的内容会变化
                                await this.props.onLoadPrev();

                                setTimeout(() => {
                                    this.fm[0].refresh();
                                }, 3000);
                            } catch (error) {
                                console.error('load prev error: ',  error);
                            } finally {
                                this.loadPreLock = false;
                            }
                        }
                    },

                    loadMore: {
                        distance: 100,
                        onLoadMore: async function () {
                            try {
                                await props.onLoadNext();
                            } catch (error) {
                                console.error('load next error: ',  error);
                            } finally {
                                this.loadEnd();
                            }
                        }
                    }
                })
            ]
        });
就像这样，页面滚动到顶部的时候我请求一个接口加载数据，加载完成后我刷新了一下，但是在页面上的表现是滚动到顶部，不能再滚动了，但是其实顶部以上的dom已经存在页面里面了，只是无法滚动下来。
我是想做上拉加载更多，下拉也加载更多。麻烦看一下怎么解决，给我一个思路也行，非常感谢！

**Comment by kele59** [comment]
@429365799 
是要做滚动到底部然后加载数据吗，可以参考一下这个 demo： #6

**Comment by HcySunYang** [comment]
@429365799 
首先这个代码看着真是很难受。。。。建议整理下格式。
我根据我的理解，尝试着解决一下你的问题。
不推荐使用 onTransMove 事件做这个事情，你可以把你的代码按照下面这段代码这样修改一下：
```javascript
            simulationScrollY({
                pullDown: {
                    use: true,
                    distance: 0,
                    onActive: async () => {
                        try {
                            // 加载数据，列表的内容会变化
                            await this.props.onLoadPrev();

                            setTimeout(() => {
                                this.fm[0].refresh();
                            }, 3000);
                        } catch (error) {
                            console.error('load prev error: ',  error);
                        } finally {
                            this.loadPreLock = false;
                        }

                    },
                    onAfter: function () {}
                }
            })
```
把逻辑挪到 pullDown.onActive 回调函数下执行。由于我只能看到你贴出来的代码段，不清楚上下文情况，上面的代码你可以做适当修改应用到你的项目中。
先看看能不能解决问题吧，不过这样是需要用户手动下拉一下才能加载。目前框架只考虑了向上的无限滚动，没有考虑向下的无限滚动。

**Comment by 429365799** [comment]
我是想做向下无限滚动，目前有没有什么思路可以做到？
