### ISSUE TITLE
中文版 vue components下面的示例demo全是404

### ISSUE THREAD

**Issue by iHinata** [HcySunYang/finger-mover#11]

**Comment by HcySunYang** [comment]
@iHinata 能否把404的链接贴出来，我这边检查过了，没有出现404的问题。

**Comment by iHinata** [comment]
个人习惯问题吧   习惯右键新窗口打开
vue components >  pulldown
直接点击： https://fmover.hcysun.me/#/zh-cn/plugins/simulation-scroll-y?id=pulldown
右键新窗口： https://fmover.hcysun.me/zh-cn/plugins/simulation-scroll-y?id=pulldown
除了 simulation-scroll-y.vue  这个链接正常，其他的全有这个毛病，
