### ISSUE TITLE
不支持安卓4.4机器啊

### ISSUE THREAD

**Issue by wulucxy** [HcySunYang/finger-mover#12]
直接报错，看不到错误信息

```
 var matrixArray = matrix.match(/[+-]?\d*[.]?\d+(?=,|\))/g);
```
显示matrix为undefined

**Comment by HcySunYang** [comment]
@wulucxy 你用的是那个插件？

**Comment by wulucxy** [comment]
@HcySunYang https://github.com/HcySunYang/finger-mover/blob/dev/dist/finger-mover.js，79行，matrix为undefined

**Comment by wulucxy** [comment]
@HcySunYang 预计什么时候修复，已经上线的页面有bug

**Comment by HcySunYang** [comment]
@wulucxy 正在排查.....

**Comment by HcySunYang** [comment]
@wulucxy 我更新了一个版本1.1.8，你那边更新一下试试。

**Comment by wulucxy** [comment]
@HcySunYang 找到原因了，4.4不支持requestAnimation，加上这个pollify就好了，https://www.paulirish.com/2011/requestanimationframe-for-smart-animating/

**Comment by HcySunYang** [comment]
@wulucxy 这就不科学了，框架是处理了requestAnimation兼容性问题的，在不支持该方法的设备中自动降级用setTimeout，并且也做过测试，代码在这里是可以看到的：https://github.com/HcySunYang/finger-mover/blob/dev/src/moved/animationframe.js
