### ISSUE TITLE
水平滚动bug

### ISSUE THREAD

**Issue by keepfool** [HcySunYang/finger-mover#13]
水平滚动，bounce设置为false时，滚动到边缘会触发translateY，导致元素飞出去了:joy:。

simulation-scroll-x.js的wrapMove方法有点问题

```javascript
inCallBack: function(currentPos) {
  currentX = currentPos.translateX
  if (!opa.bounce) {
    if (currentX >= leftLimit) {
      moved.stop((currentPos) => {
        currentX = leftLimit
        moved.transform(el, 'translateY', currentX)
      })
    }
    if (currentX <= rightLimit) {
      moved.stop((currentPos) => {
        currentX = rightLimit
        moved.transform(el, 'translateY', rightLimit)
      })
    }
  }
}
```

`moved.transform(el, 'translateY', currentX)`和`moved.transform(el, 'translateY', rightLimit)`中的translateY应该更改为translateX，这是水平滚动，不是垂直滚动:sweat_smile:。

**Comment by HcySunYang** [comment]
@keepfool 感谢使用，感谢指正，这是一个低级错误。我将修正并发布1.1.9版本，详细请查看：https://github.com/HcySunYang/finger-mover/releases/tag/1.1.9
