### ISSUE TITLE
水平滚动到边缘时，currentX和元素的实际translateX不一致

### ISSUE THREAD

**Issue by keepfool** [HcySunYang/finger-mover#14]
@HcySunYang 
场景还原步骤：
1. 页面采用iPhone 6的模拟尺寸（375*667）
2. 水平滚动放了6个长方形，每个长方形尺寸为200*100，总宽度为1200
3. 滚动到最右边时，滚动容器的**translateX为-825px**（计算方式：375 - 1200）

一直到前3步都是正常的

**4. 向左拉动到边缘时，滚动容器的translateX和currentX不一致。
举例说明：向左拉25px，这时translateX是-850px，但在makeMove方法中取到的currentX确是-875**

```javascript
// simulation-scroll-x.js
makeMove (tev) {
  let tweenS

  moveTime = tev.transTime
  currentX = currentX + tev.distanceX

  transTargetX = currentX + tev.transDistanceX

  // -50
  console.log(tev.distanceX)
  // -875
  console.log(currentX)
}
```

下面两幅截图也描述了此问题，请参考之。
![滚动到最右边](http://i.imgur.com/x7gWgji.png)

![再向左拖动25px](http://i.imgur.com/XiZd5rw.png)

**Comment by HcySunYang** [comment]
@keepfool 感谢指正，这里应该改成：

```javascript
currentX = moveTarget
```

其中 `moveTarget` 是 `move` 方法中的局部变量。为了能够访问，将其变为更加顶层的局部变量。实际上在 `simulation-scroll-y.js` 中就是这样做的。
另外这段时间公司的业务有点忙，很早看到你的 issue，今天才来仔细查看。。。。

**Comment by keepfool** [comment]
@HcySunYang got it, thanks.
