### ISSUE TITLE
横向滚动的时候，动态设置width后不能滚动

### ISSUE THREAD

**Issue by zhuyuanwen** [HcySunYang/finger-mover#17]
我查看了文档，demo里面将width设置成3000px，滚动的时候到3000了就停止滚动。
```
#scroll-box {
    background: #19bbff;
    width: 3000px;
  }
```
但是，如果我将width设置成300px，然后用js动态将width改为3000px，宽度可以设置成功，但是却无法滚动。请问有什么办法可以解决呢？
因为需要的运用场景是，要滚动的内容是动态生成的，我预先不知道要将width设置成多少，只有在获取到data之后，动态将width设置成需要的大小。

**Comment by zhuyuanwen** [comment]
@HcySunYang

**Comment by HcySunYang** [comment]
@zhuyuanwen 
https://fmover.hcysun.me/#/zh-cn/plugins/simulation-scroll-x?id=refreshsize
调用 refreshsize() 试一下

**Comment by zhuyuanwen** [comment]
@HcySunYang 
试了，成功了。谢谢！
