### ISSUE TITLE
fmover-slide-x 初始化问题

### ISSUE THREAD

**Issue by wangguohao** [HcySunYang/finger-mover#18]
https://github.com/HcySunYang/finger-mover/blob/59f22e53b9f56722d3c3ad7f5273817eccccc7e1/src/plugins/fmover-slide-x/fmover-slide-x.js#L178

slide内容过于复杂时不止一个div，此处会导致页面显示异常，建议调整为
```
slideEls = el.childNodes;
```

**Comment by HcySunYang** [comment]
c50b621d073c132648606308c313a48c27e48221
