### ISSUE TITLE
onChangeStart 方法有个BUG

### ISSUE THREAD

**Issue by kele59** [HcySunYang/finger-mover#2]
"finger-mover": "^1.1.0",
 "fmover-slide-x": "^1.1.0",

```html
<div class="slide-wrap">
    <div>图1</div> 
    <div>图2</div>
    <div>图3</div>
 </div>
```
```javascript
new Fmover({
      el: '.slide-wrap',
      plugins: [
        fmoverSlideX({
          loop: false,
          onChangeStart(index){
            console.log(index)
          }
        })
      ]
    })
```
理论上，从「图1」开始，用手指从左到右滑动，文字会依次切换成「图2，图3」，
 控制台上会依次输出 2，3
但是滑到最后一张图的时候，继续向左滑动，文字保持「图3」不变，但是控制台会输出 1

![bug](https://cloud.githubusercontent.com/assets/14342431/26299571/d8c9a6a4-3f0d-11e7-9bee-34e1be892649.gif)

**Comment by HcySunYang** [comment]
Thank you for asking this question,I have solved and released a small version.
Please see https://github.com/HcySunYang/finger-mover/releases/tag/1.1.3

**Comment by kele59** [comment]
I'm sorry, I have been using Chinese to talk to you, because the Chinese document very well written, so I always thought you were Chinese.

**Comment by HcySunYang** [comment]
@zaxlct I am really Chinese, haha

**Comment by kele59** [comment]
@HcySunYang 我.......
