### ISSUE TITLE
手指移到滚动区域外层的固定元素，回弹会失效

### ISSUE THREAD

**Issue by jaqen404** [HcySunYang/finger-mover#24]
```html
<style>
...
.ba {
            position: fixed;
            height: 100px;
            background: #000;
            color:#fff;
            z-index: 1000;
            right:0;
            width: 50%;
            top:50%;
        }
</style>
```
```html
<div id="box">
    <div class="ba">bababab</div>
    <div id="scroll-box">
        <div class="pull-down-dom">Pull down to refresh</div>
        <div class="content"></div>
    </div>
</div>
```
![wx20180201-215059](https://user-images.githubusercontent.com/6075540/35681931-02df6fa0-079a-11e8-9600-4abb6d784181.png)

用官网上的例子，再在外层加一个固定的元素（黑块 ba）。
下拉直至手指到达黑块，在黑块内左右滑动多次，会触发simulation-scroll-y中的refresh方法，但是滚动区域不会回弹回去。断点后发现，是ismoving还是true。

![scroll-ismoving-bug](https://user-images.githubusercontent.com/6075540/35681785-75584a6c-0799-11e8-90a6-1e35a0c636af.png)

----------------------------------
以上是用demo重现，实战项目中更明显，手指滑到外层固定元素就会重现，不需要左右滑动。断点看了，原因应该是一样的，也是ismoving为true。

**Comment by HcySunYang** [comment]
已经解决了，安装 `simulation-scroll-y` `1.3.2` 版本
https://github.com/HcySunYang/finger-mover/releases/tag/1.3.2
