### ISSUE TITLE
当浏览器有滚动条时，finger-mover滚动失效

### ISSUE THREAD

**Issue by lixiaofeng666** [HcySunYang/finger-mover#7]
https://codepen.io/pnoonlee/pen/awmvPR
情况是这样:
页面出现滚动条,也就是页面高度>window.innerHeight
先进行页面的滚动,滚动到只显示一行123时,这个时候再滚动123的区域,滚动就失效了 :(

**Comment by HcySunYang** [comment]
@PhoonLee 这的确是一个bug，我已经进行了修复，并发布了一个小版本1.1.6： https://github.com/HcySunYang/finger-mover/releases/tag/1.1.6。
这个问题的原因在于DOM原生的方法 document.elementFromPoint(x, y) 接收的坐标值为 clientX/clientY，然而我传递的是 pageX/pageY。
感谢你能够提出问题，之后在使用框架的过程中遇到任何问题都可及时提出，我会尽力解决。
